version: '3.8'
services:
  splunk-forwarder:
    image: splunk/universalforwarder:latest
    container_name: splunk-forwarder
    environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_PASSWORD=changeme
    volumes:
    - /var/log/audit/audit.log:/var/log/audit/audit.log:ro
    restart: unless-stopped
