version: '3.8'
services:
  splunk:
    image: splunk/universalforwarder:latest
    container_name: splunk-forwarder
    environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_PASSWORD=changeme
    volumes:
    - ./splunk_config:/opt/splunk/etc
    - /var/log:/host_logs:ro
    restart: unless-stopped
